import React from "react";
import Layout from "../layouts";

function privacy() {
  return (
    <Layout>
      <section className="privacy" id="privacy">
        <div className="container">
          <article className="privacy py-4">
            <h2 className="py-2 pb-2 fw-bold">Privacy Policy</h2>
            <p className="py-2">Updated at 2022.10.01</p>
            <p className="py-2">
              Hunterswall (“we”, “our”, or “us”) is committed to protecting your
              privacy. This Privacy Policy explains how your personal
              information is collected, used, and disclosed by Hunterswall.
              <br />
              <br /> This Privacy Policy applies to our website,
              thehunterswall.com, and its associated domains (collectively, our
              “Services”). By accessing or using our Services, you signify that
              you have read, understood, agree to our collection, storage, use,
              and disclosure of your personal information as described in this
              Privacy Policy and our Term of Service.
            </p>
            <h6 className="py-2 fw-bold">Definitions and key terms</h6>
            <p className="py-2">For this Privacy Policy:</p>
            <ul className="">
              <li className="py-2">
                <strong>Cookie:</strong> Small amount of data generated by a
                website and saved by your browser. It is used to identify your
                browser, and provide analytics, remember information about such
                as your language preference and your login information.
              </li>
              <li className="py-2">
                <strong>Companies:</strong> When this policy mentions “Company,”
                “us,” or “our,” it refers to Hunterswall Strategies Limited, 2,
                Egbatedo Close, off Iju Road, Ifako Ijaiye, Lagos. That is
                responsible for your information under this Privacy Policy.
              </li>
              <li className="py-2">
                <strong>Country:</strong> Where Hunterswall or the
                owners/founders of Hunterswall are based, in this case is
                Nigeria.
              </li>
              <li className="py-2">
                <strong>Customers:</strong> refers to the company, organization
                or person that signs up to use Hunterswall Service to manage the
                relationships with your consumers or service users.
              </li>
              <li className="py-2">
                <strong>Device:</strong> any internet connected device such as
                phone, tablet, computer, or any other device that can be used to
                visit Hunterswall and use the services.
              </li>
              <li className="py-2">
                <strong>IP address:</strong> Every device connected to the
                internet is assigned a number known as internet protocol (IP)
                address. These numbers are usually assigned in geographical
                blocks. An IP address can often be used to identify the location
                from which a device is connecting to the internet.
              </li>

              <li className="py-2">
                <strong>Personnel:</strong> refers to those individuals who are
                employed by Hunterswall or are under contract to perform service
                on behalf of one of the parties.
              </li>

              <li className="py-2">
                <strong>Personal Date:</strong> any information that directly or
                indirectly, or in connection with other information – including
                a personal identification number – allow for the identification
                or identification of the natural person.
              </li>

              <li className="py-2">
                <strong>Service:</strong> refers to service provider by
                Hunterswall as described in the relative terms (if available)
                and on this platform.
              </li>

              <li className="py-2">
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </li>

              <li className="py-2">
                <strong>Website:</strong> Hunterswall’s site, which can be
                accessed via this URL: thehunterswall.com
              </li>

              <li className="py-2">
                <strong>You:</strong> a person or entity that is registered with
                Hunterswall to use the Services.
              </li>
            </ul>
            <h6 className="py-2 fw-bold">What Information Do We Collect? </h6>
            <p className="py-2">
              We collect information from you when you visit our service,
              register, subscribe or fill a form.
            </p>
            <ul className="">
              <li className="py-2">Name</li>
              <li className="py-2">Phone Number</li>
              <li className="py-2">Email Address</li>
              <li className="py-2">Mailing Address</li>
              <li className="py-2">Debit/Credit Card Numbers</li>
              <li className="py-2">Age</li>
              <li className="py-2">Password</li>
            </ul>
            <h6 className="py-2 fw-bold">
              How do we use the information we collect?
            </h6>
            <p className="py-2">
              Any information we collect from you may be used to in any of the
              following ways:
            </p>
            <ul className="">
              <li className="py-2">To personalize your experience</li>
              <li className="py-2">To improve our service</li>
              <li className="py-2">To personalize your experience</li>
              <li className="py-2">To improve customer service</li>
              <li className="py-2">To process transaction</li>
              <li className="py-2">
                To administer a contest, promotion, survey, and other site
                feature
              </li>
              <li className="py-2">To send periodic mails.</li>
            </ul>
            <h6 className="py-2 fw-bold">
              When do we use customer information from third parties?{" "}
            </h6>
            <p className="py-2">
              We receive information from third parties when you contact us. For
              example, when you submit your email address to us to show interest
              in becoming our users, we receive information from a third party
              that provides automated fraud detection services to us. We also
              occasionally collect information that is made publicly available
              on social media websites. You can control how much your
              information social media websites make public by visiting these
              websites and changing your privacy settings.
            </p>
            <h6 className="py-2 fw-bold">
              Do we share the information we collect with third party?
            </h6>
            <p className="py-2">
              We may share the information that we collect, both personal and
              non-personal, with third parties such as advertisers, content
              sponsors, promotional and marketing partners, and others who
              provide our content or whose products and services we think may
              interest you. We may also share It with our current and future
              affiliated companies and business partners, and if we are involved
              with a merger, assets sales or other business organization, we may
              also share or transfer your personal and non-personal information
              to our successors-in-interest.
              <br />
              <br /> We may engage trusted party service providers to perform
              functions and provide services to us, such as hosting and
              maintaining our services, and our service, database storage and
              management, e-mail management, storage marketing, credit card
              processing, customers service and fulfilling orders for products
              and services you may purchase through our platform. We will likely
              share your personal information, and possibly some non-personal
              information with these third parties to enable them to perform
              these services for us and for you.
              <br />
              <br /> We may share some of our log file data, including IP
              addresses, for analytics purposes with third parties such as web
              analytics partners, application developers, and ad networks. If
              your IP address is shared, it may be used to estimate general
              location and other technographics such as connection speed,
              whether you have visited the services in a shared location, and
              type of device you used to visit the service. They may aggregate
              the information about our advertising and what you see on the
              service and then provide auditing, research and reporting for us
              and our advertisers.
              <br />
              <br /> We may also disclose personal and non-personal information
              about you to government or law enforcement officials or private
              parties as we, in our sole discretion, believe necessary or
              appropriate in order to respond to claims, legal process
              (including subpoenas), to protect our rights and interests or
              those of a third party, the safety of the public or any person, to
              prevent or stop any illegal, unethical, or legal actionable
              activity, or to otherwise comply with applicable court orders,
              laws, rules and regulations.
            </p>
            <h6 className="py-2 fw-bold">
              Where and when is information collected from customers and end
              users?
            </h6>
            <p className="py-2">
              We will collect personal information that you submit to us. We may
              also receive information about you from third parties as described
              above.
            </p>
            <h6 className="py-2 fw-bold">How do we use your email address?</h6>
            <p className="py-2">
              By submitting your email address on this website, you agree to
              receive email from us. You can cancel your participation in any of
              these email lists at any time by clicking on the opt-out link or
              other unsubscribed option that is included in the respective
              email. We do not send unsolicited commercial emails, because we
              hate spam as much as you do. By submitting your email address, you
              also agree to allow us to use your email address for customer
              audience targeting on sites like Facebook, where we display custom
              advertising to specific people who have opted-in to receive
              communication from us. Email address submitting through the order
              processing page will be used for the sole purpose of sending you
              information and updates pertaining to your order. If, however, you
              have provided the same email to us through another method, we may
              use it for any of the purpose stated in this Policy. Note: if at
              any time, you would like us to unsubscribe from receiving future
              emails, we include detailed unsubscribe instructions at the bottom
              of each email.
            </p>
            <h6 className="py-2 fw-bold">
              Could my information be transferred to another country?
            </h6>
            <p className="py-2">
              We are incorporated in Nigeria. Information collected via our
              website, through direct interactions with you, or from use of our
              help services may be transferred from time to time to our offices
              or personnel, or to third parties, located throughout the world,
              and may be viewed and hosted anywhere in the world, including
              countries that may not have laws of general applicability
              regulating the use and transfer of such data. To the fullest
              extent allowed by applicable law, by using any of the above, you
              voluntarily consent to the transborder transfer and hosting of
              such information.
            </p>
            <h6 className="py-2 fw-bold">
              Is the information collected through our service secure?
            </h6>
            <p className="py-2">
              We take precautions to protect the security of your information.
              We have physical, electronic, and managerial procedures to help
              safeguard, prevent unauthorized access, maintain data security,
              and correctly use your information. However, neither people nor
              security system are foolproof, including encryption systems. In
              addition, people can commit intentional crimes, make mistakes, or
              fail to follow policies. Therefore, while we use reasonable
              efforts to protect your personal information, we cannot guarantee
              its absolute security. If applicable law imposes any
              non-disclaimable duty to protect your personal information, you
              agree that intentional misconduct will be the standards used to
              measure our compliance with that duty.
            </p>
            <h6 className="py-2 fw-bold">
              Can I update or correct my information?
            </h6>
            <p className="py-2">
              The rights you have to request updates or corrections to the
              information we collect depend on your relationship with us.
              Personnel may update or correct their information as detailed in
              our internal company employment policies. Customers have the
              rights to request the restriction of certain uses and disclosures
              of personally identifiable information as follows. You can contact
              us in order to (1) update or correct your personal identifiable
              information, (2) change your preferences with respect to
              communications and other information you receive from us, or (3)
              delete the personally identifiable information maintained about
              you on our systems (subject to the following paragraph), by
              canceling your account. Such updates, corrections, changes, and
              deletions will have no effect on other information that we
              maintain, or information that we may have provided to third
              parties in accordance with this Privacy Policy prior to such
              update, correction, change, or deletion. To protect your privacy
              and security, we may take reasonable steps (such as requesting
              unique password0 to verify your identity before granting your
              profile access or making corrections. You are responsible for
              maintaining the secrecy of your unique password, and account
              information at all times. You should be aware that it is not
              technologically possible to remove each record of the information
              you have provided to us from our system. The need to back up our
              systems to protect information from inadvertent loss means that a
              copy of your information may exist in a non-erasable form that
              will be difficult or impossible for us to locate. Promptly after
              receiving your request, all personal information stored in
              database we actively use, and other readily searchable media will
              be updated., corrected, changed or deleted, as appropriate, as
              soon as and to extent reasonably and technically practicable. If
              you are an end user and wish to update, delete, or receive any
              information we have about you, you may do so by contacting the
              organization of which you are a customer.{" "}
            </p>
            <h6 className="py-2"> Personnel</h6>
            <p className="py-2">
              If you are one of our workers or applicants, we collect
              information you voluntarily provide to us. We use the information
              collected for Human Resources purposes in order to administer
              benefits to workers and screen applicants. You may contact us in
              order to (1) update or correct your information, (2) change your
              preferences with respect to communication and other information
              you receive from us, or (3) receive a record of the information we
              have relating to you. Such updates, corrections, changes and
              deletions will have no effect on other information that we
              maintain, or information that we have provided to third parties in
              accordance with this Privacy Policy prior to such updates,
              correction, change or deletion.{" "}
            </p>
            <h6 className="py-2 fw-bold">Sale of Business</h6>
            <p className="py-2">
              We reserve the right to transfer information to a third party in
              the event of a sale, merger or other transfer of all substantially
              all of the assets of us or any of its Corporate Affiliates (as
              defined herein), or other portion of us or any of its Corporate
              Affiliates to which the Service relates, or in the event that we
              discontinue our business or file a petition or have filed against
              us a petition in bankruptcy, reorganization or similar proceeding,
              provided that the third party agrees to adhere to the terms of
              this Privacy Policy.
            </p>
            <h6 className="py-2 fw-bold">Affiliates</h6>
            <p className="py-2">
              We may disclose information (including personal information) about
              you to our Corporate Affiliates. For purpose of this Privacy
              Policy, “Corporate Affiliates” means any person or entity which
              directly or indirectly controls, is controlled by or is under
              common control with us, whether by ownership or otherwise. Any
              information relating to you that we provide to our Corporate
              Affiliates will be treated by those Corporate Affiliates in
              accordance with the terms of this Privacy Policy.{" "}
            </p>
            <h6 className="py-2 fw-bold">
              How long do we keep your information?{" "}
            </h6>
            <p className="py-2">
              We keep your information only so long as we need it to provide
              service to you and fulfil the purposes described in this policy.
              This is also the case for anyone that we share your information
              with and who carries our services on our behalf. When we no longer
              need to use your information and there is no need for us to keep
              it comply with our legal or regulatory obligations, we’ll either
              remove it from our systems or depersonalize it so that we can’t
              identify you.
            </p>
            <h6 className="py-2 fw-bold">
              How do we protect your information?
            </h6>
            <p className="py-2">
              We implement a variety of security measures to maintain the safety
              of your personal information when you subscribe or enter, submit,
              or access your personal information. We offer the use of a secure
              server.
              <br />
              <br /> All supplied sensitive/credit information is transmitted
              via Secure Socket Layer (SSL) technology and then encrypted into
              our Payment gateway provider(s) database only to be accessible by
              those authorized with special access rights to such systems, are
              required to keep the information confidential. After a
              transaction, your private information (credit cards, social
              security numbers, financials, etc.) is never kept on file. We
              cannot, however, ensure or warrant the absolute security of any
              information you transmit to us or guarantee that your information
              on the Service may not be accessed, disclosed, altered, or
              destroyed by a breach of any of our physical, technical, or
              managerial safeguards.
            </p>
            <h6 className="py-2 fw-bold">Governing Law</h6>
            <p className="py-2">
              The laws of Nigeria, excluding its conflicts of law rules, shall
              govern this agreement and your use of our service. Your use of our
              service may also be subject to other local, state, national, or
              international laws.
            </p>
            <h6 className="py-2 fw-bold">Your Consent</h6>
            <p className="py-2">
              By using our service, registering account, or making a purchase,
              you consent to this Privacy Policy.
            </p>
            <h6 className="py-2 fw-bold">Links to other websites</h6>
            <p className="py-2">
              This Privacy Policy applies only to the Services. The services may
              contain links to other websites not operated or controlled by. We
              are not responsible for the extent, accuracy or opinions expressed
              in such as websites are not investigated, monitored, or checked
              for accuracy or completeness by us. Please remember that when you
              use a link go from the Services to another website, our Privacy
              Policy is no longer in effect. Your browsing and interaction on
              any other websites, including those that have a link on our
              platform, is subject to that website’s own rules and policies.
              Such third parties may use their own cookies or other methods to
              collect information about you.
            </p>
            <h6 className="py-2 fw-bold">Cookies</h6>{" "}
            <p className="py-2">
              We use “Cookies” to identify the areas of our websites that you
              have visited. A Cookie is a small piece of data stored on your
              computer or mobile device by our web browser. We use Cookies to
              personalize Content that you see on our website. Most web browsers
              can be set to disable the use of Cookies. However, if you disable
              Cookies, you may not be able to access functionality on our
              website correctly or at all. We never place Personally
              Identifiable Information in Cookies.
            </p>
            <h6 className="py-2 fw-bold">Remarketing Services</h6>{" "}
            <p className="py-2">
              We use marketing services. What is remarketing? In digital
              marketing, remarketing (or retargeting) is the practice of serving
              ads across the internet to people who have already visited your
              website. It allows your company to seem like they are “following”
              people around the internet by serving ads on the website and
              platforms they use most.
            </p>
            <h6 className="py-2 fw-bold">Payment Details</h6>
            <p className="py-2">
              In respect to any credit card or other payment processing details
              you have provided us, we commit that this confidential information
              will be stored in the most secure manner possible.
            </p>
            <h6 className="py-2 fw-bold">Kid’s Privacy</h6>
            <p className="py-2">
              We do not address anyone under age 13. We do not knowingly collect
              personally identifiable information from anyone under the age of
              13. If you are a parent or guardian and you are aware that your
              child has provided us with personal data, please contact us. If we
              become aware that we have collected Personal Data from any one
              under the age of 13 without verification of parental consent. We
              take steps to remove the information from our servers.
            </p>
            <h6 className="py-2 fw-bold">Changes To Our Privacy Policy</h6>
            <p className="py-2">
              If we decide to change our privacy policy, we will post those
              changes on this page, and/or update the Privacy Policy
              modification date.
            </p>
            <h6 className="py-2 fw-bold">Third-Party Services</h6>
            <p className="py-2">
              We may display, include, or make available third-party content
              (including data, information, applications and other products
              services) or provide links to third-party websites or services
              (“Third-Party Services”). You acknowledge and agree that we shall
              not be responsible for any Third-Party Services, including their
              accuracy, completeness, timeliness, validity, copyright
              compliance, legality, decency, quality, or any other aspect
              thereof. We do not assume and shall not have any liability or
              responsibility to you or any other person or entity for any
              Third-Party Services.
              <br />
              <br /> Third-Party services and links thereto are to be provided
              solely as a convenience to you and you access and use them
              entirely at your own risk and subject to such third parties’ terms
              and conditions.
            </p>
            <h6 className="py-2 fw-bold">Tracking Technologies</h6>
            <ul className="list">
              <li className="py-2">
                <p>Cookies</p>
                <span>
                  We use Cookies to enhance the performance and functionality of
                  our service but are non-essential to their use. However,
                  without these Cookies, certain functionality like videos may
                  become unavailable or you would be required to enter your
                  login details every time you visit our service as we would not
                  be able to remember that you had logged in previously.
                </span>
              </li>

              <li className="py-2">
                <p>Local Storage</p>
                <span>
                  Local storage sometimes known as DOM storage, provides web
                  apps with method and protocols for storing client-side data.
                  Web storage supports persistent data storage, similar to
                  cookies but with a greatly enhanced capacity and no
                  information stored in the HTTP request header.
                </span>
              </li>
            </ul>
          </article>
        </div>
      </section>
    </Layout>
  );
}

export default privacy;
