import React from "react";
import Layout from "../layouts";

function terms() {
  return (
    <Layout>
      <section>
        <div className="container">
          <article className="terms py-4">
            <h2 className="py-2 pb-2 fw-bold">Terms & Conditions</h2>
            <h6 className="py-2 pb-2 fw-bold">General Terms</h6>
            <p className="pb-2">
              By accessing and subscribing with Hunterswall Strategies Limited,
              you confirm that you are in agreement with and bound by the terms
              of service contained in the Terms and Conditions outlined below.
              These terms apply to the entire website and any email or other
              types of communication between you and Hunterswall Strategies
              Limited.
            </p>
            <p className="pb-2">
              Under no circumstances shall team be liable for any direct,
              indirect, special, incidental, or consequential damages,
              including, but not limited to loss of capital, profit, or data.{" "}
            </p>
            <p className="py-2">
              These Terms & Conditions are a contract between you and
              Hunterswall Strategies Limited (referred to in these Terms &
              Conditions as “Hunterswall”, “us”, “we”, or “our”), the provider
              of the Hunterswall website and services accessible from
              Hunterswall website (which are collectively referred to in these
              Terms & Conditions as the “Hunterswall Service”).
            </p>
            <h6 className="py-2  fw-bold">Definitions and key terms</h6>
            <p>For this Terms and Conditions:</p>
            <ul className="">
              <li className="py-2">
                <strong>Cookie:</strong> Small amount of data generated by a
                website and saved by your browser. It is used to identify your
                browser, and provide analytics, remember information about such
                as your language preference and your login information.
              </li>
              <li className="py-2">
                <strong>Companies:</strong> When this policy mentions “Company,”
                “us,” or “our,” it refers to Hunterswall Strategies Limited, 2,
                Egbatedo Close, off Iju Road, Ifako Ijaiye, Lagos. That is
                responsible for your information under this Privacy Policy.
              </li>
              <li className="py-2">
                <strong>Country:</strong> Where Hunterswall or the
                owners/founders of Hunterswall are based, in this case is
                Nigeria.
              </li>
              <li className="py-2">
                <strong>Customers:</strong> refers to the company, organization
                or person that signs up to use Hunterswall Service to manage the
                relationships with your consumers or service users.
              </li>
              <li className="py-2">
                <strong>Device:</strong> any internet connected device such as
                phone, tablet, computer, or any other device that can be used to
                visit Hunterswall and use the services.
              </li>
              <li className="py-2">
                <strong>IP address:</strong> Every device connected to the
                internet is assigned a number known as internet protocol (IP)
                address. These numbers are usually assigned in geographical
                blocks. An IP address can often be used to identify the location
                from which a device is connecting to the internet.
              </li>

              <li className="py-2">
                <strong>Personnel:</strong> refers to those individuals who are
                employed by Hunterswall or are under contract to perform service
                on behalf of one of the parties.
              </li>

              <li className="py-2">
                <strong>Personal Date:</strong> any information that directly or
                indirectly, or in connection with other information – including
                a personal identification number – allow for the identification
                or identification of the natural person.
              </li>

              <li className="py-2">
                <strong>Service:</strong> refers to service provider by
                Hunterswall as described in the relative terms (if available)
                and on this platform.
              </li>

              <li className="py-2">
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </li>

              <li className="py-2">
                <strong>Website:</strong> Hunterswall’s site, which can be
                accessed via this URL: thehunterswall.com
              </li>

              <li className="py-2">
                <strong>You:</strong> a person or entity that is registered with
                Hunterswall to use the Services.
              </li>
            </ul>
            <h6 className="py-2  fw-bold">Payment</h6>
            <p className="py-2">
              If you pay for any of our services or subscriptions, you agree to
              pay all fees, commission, or charges to your account for the
              Service in accordance with the fees, commission or charges and
              billing terms in effect at the time each fee, commission, or
              charge is due and payable. Your payment provider agreement governs
              your use of the designated credit/debit card account, and you must
              refer to that agreement and not these Terms to determine your
              rights and liabilities with respect to your Payment Provider. By
              providing with your debit/credit card number and associated
              payment information, you agree that we are authorized to verify
              information immediately, and subsequently invoice your account for
              all the fees, commission, or charges due and payable to us
              hereunder and no additional notice or consent is required. You
              agree to immediately notify us of any change in your billing
              address to the debit/credit card for payment hereunder. We reserve
              the right at any time to change subscription’s price as the market
              dictates.
            </p>
            <h6 className="py-2  fw-bold">Your Suggestions</h6>
            <p className="py-2">
              Any feedback, comments, ideas, improvements, or suggestions
              (collectively “Suggestions”) provided by you to us with respect to
              the service shall remain the sole and exclusive property of us. We
              shall be free to use, copy, modify, publish, or redistribute the
              Suggestions for any purpose and in any way without any credit or
              any compensation to you.
            </p>
            <h6 className="py-2  fw-bold">Your Consent</h6>
            <p className="py-2">
              We have updated our Terms and Conditions to provide you with
              complete transparency into what is being set when you visit our
              site and how it’s being used. By using our service, registering an
              account, or making a purchase, you hereby consent to our Terms and
              Conditions.
            </p>
            <h6 className="py-2  fw-bold">
              Links to other websites Our service may contain links to other{" "}
            </h6>
            <p className="py-2">
              websites that are not operated by Us. If You click on a
              third-party link, You will be directed to other third party’s
              site. We strongly advise you to review the Terms & Conditions of
              every site You visit. We have no control over and assume no
              responsibility for the content, Terms and Conditions or practices
              of any third-party sites or services.
            </p>
            <h6 className="py-2 fw-bold">Cookies</h6>
            <p className="py-2">
              {" "}
              We use “Cookies” to identify the areas of our websites that you
              have visited. A Cookie is a small piece of data stored on your
              computer or mobile device by our web browser. We use Cookies to
              personalize Content that you see on our website. Most web browsers
              can be set to disable the use of Cookies. However, if you disable
              Cookies, you may not be able to access functionality on our
              website correctly or at all. We never place Personally
              Identifiable Information in Cookies.
            </p>
            <h6 className="py-2 fw-bold">Changes to Our Terms & Conditions</h6>
            <p className="py-2">
              You acknowledge and agree that we may stop (permanently or
              temporarily) providing the Service (or any features within the
              Service) to you or to users generally at our sole discretion,
              without prior notice to you. You may stop using the Service at any
              time. You do not need to specifically inform us when you stop
              using the Service. You acknowledge and agree that if we disable
              access to your account, you may be prevented from accessing the
              Service, you account details or any file or other materials which
              is contained in your account. If we decide to change our Terms &
              Conditions, we will post those changes on this page, and/or update
              the Terms & Conditions modification date below.
            </p>
            <h6 className="py-2 fw-bold">Modifications to Our Service</h6>
            <p className="py-2">
              {" "}
              We reserve the right to modify, suspend or discontinue,
              temporarily or permanently, the service or any service to which it
              connects, with or without notice and without liability to you.
            </p>
            <h6 className="py-2 fw-bold">Updates to Our Services</h6>
            <p className="py-2">
              {" "}
              We may from time to time provide enhancements or improvements to
              features/functionality of the service, which may include patches,
              bug fixes, updates, upgrades, and other modifications (“Updates”).
              Update may modify or delete certain features and/or
              functionalities of the services. You agree that we have no
              obligation to (i) to provide any updates, or (ii) continue to
              provide or enable any features and/or functionalities of the
              service to you. You further agree that all updates will be (i)
              deemed to constitute an integral part of the service, and (ii)
              subject to the terms and conditions of this agreement.
            </p>
            <h6 className="py-2 fw-bold">Third-Party Services</h6>
            <p>
              We may display, include, or make available third-party content
              (including data, information, applications and other products
              services) or provide links to third-party websites or services
              (“Third-Party Services”).
              <br /> <br /> You acknowledge and agree that we shall not be
              responsible for any Third-Party Services, including their
              accuracy, completeness, timeliness, validity, copyright
              compliance, legality, decency, quality, or any other aspect
              thereof. We do not assume and shall not have any liability or
              responsibility to you or any other person or entity for any
              Third-Party Services. <br />
              <br />
              Third-Party services and links thereto are to be provided solely
              as a convenience to you and you access and use them entirely at
              your own risk and subject to such third parties’ terms and
              conditions.
            </p>
            <h6 className="py-2 fw-bold">Term and Termination</h6>
            <p className="py-2">
              This agreement shall remain in effect until terminated by you or
              us. We may, in its sole discretion, at any time and for any or no
              reason, suspend or terminate this Agreement with or without prior
              notice. This Agreement will terminate immediately, without prior
              notice from us, in the event that you fail to comply with any
              provision of this Agreement. You may also terminate this Agreement
              by deleting the service and all copies there of this service from
              your computer. Termination of this Agreement will not limit any of
              our rights or remedies at law or in equity in case of breach by
              you (during the term of this Agreement) of any your obligations
              under the present Agreement.
            </p>
            <h6 className="py-2 fw-bold">Term and Termination</h6>
            <p className="py-2">
              If you are a copyright owner or such owner’s agent and believe any
              material from us constitutes infringement on your copyright,
              please contact us setting forth the following information: (a) a
              physical or electronic signature of the copyrights owner or a
              person authorized to act on his behalf; (b) identification of the
              material that is claimed to be infringing; (c) your contact
              information, including your address, telephone number, and an
              email; (d) a statement by you that you have a good faith belief
              that use of the material is not authorized by the copyright
              owners; (e) the state that the information in the notification is
              accurate, and, under penalty of perjury you are authorized to act
              on behalf of the owner.{" "}
            </p>
            <h6 className="py-3 fw-bold">Investment</h6>{" "}
            <p className="py-2">
              Past performance does not guarantee future results. we emphasize
              that investments are subject to fluctuation in the market, while
              some can also be affected by natural disasters. Please read the
              scheme information and related documents carefully before
              committing your funds. Economic and industry conditions can make
              equities fluctuate, which could make your original investment
              reduce or total go to zero in value. Please consider your specific
              risk tolerance or contact your financial adviser before choosing a
              category.
            </p>
            <h6 className="py-2 fw-bold">Indemnification</h6>{" "}
            <p className="py-2">
              You agree to indemnify and hold us and our parents, subsidiaries,
              affiliates, officers, employees, agents, partners, and licensors
              (if any) harmless from any claim or demand, including reasonable
              attorneys’ fees, due to or arising out of your; (a) use of
              service; (b) violation of this Agreement or any law or regulation;
              or (c) violation of any right of a third party.
            </p>
            <h6 className="py-2 fw-bold">Severability</h6>{" "}
            <p>
              If any provision of this Agreement is held to be unenforceable or
              invalid, such provision will be changed and interpreted to
              accomplish the objectives of such provision to the greatest extent
              possible under applicable law and the remaining provisions will
              continue in full force and effect.
              <br /> <br /> This Agreement, together with the Privacy Policy and
              any legal notices published by us on the Services, shall
              constitute the entire agreement between you and us concerning the
              Services. If any provision of this Agreement is deemed invalid by
              a court of competent jurisdiction, the invalidity of such
              provision shall not affect the validity of the remaining
              provisions of this Agreement, which shall remain in full force and
              effect. No waiver of any term of this Agreement shall be deemed a
              further or continuing waiver of such term or any other term, and
              our failure to assert any right or provision under this Agreement
              shall not constitute a waiver of such right or provision. You and
              Us agree that any cause of action arising out of or related to the
              services must commence within one (1) year after the cause of
              action accrues, such cause of action is permanently barred.
            </p>
            <h6 className="py-2 fw-bold">Waiver</h6>{" "}
            <p className="py-2">
              Excepts as provided herein, the failure to exercise a right to
              acquire performance of an obligation under this agreement shall
              not affect a party’s liability to exercise such right or require
              such performance at any time thereafter nor shall be the waiver of
              a breach constitute waiver of any subsequent breach.
              <br />
              <br /> No failure to exercise, and no delay in exercising, on the
              part of either party, any right or any power under this Agreement
              shall operate as a waiver of that right or power. Nor shall any
              single or partial exercise of any right or power under tis
              Agreement preclude further exercise of that or any other right
              granted herein. In the event of a conflict between this Agreement
              and any applicable purchase or other terms, the term of this
              Agreement shall govern.
            </p>
            <h6 className="py-2 fw-bold">Amendment to this Agreement</h6>{" "}
            <p className="py-2">
              We reserve the right, at its sole discretion, to modify or replace
              this Agreement at any time. If a revision is material, we will
              provide at least 30 days’ notice prior to any new terms taking
              effect. What constitute a material change will be determined at
              our sole discretion. By continuing to access or use our service
              after any revisions become effective, you agree to be bound by the
              revised terms. If you do not agree to the new terms, you are no
              longer authorized to use our service.
            </p>
            <h6 className="py-2 fw-bold">Entire Agreement</h6>{" "}
            <p className="py-2">
              The agreement constitutes the entire agreement between you and us
              regarding the use of the service and supersedes all prior and
              contemporaneous written or oral agreement between and us. You may
              be subject to additional terms and conditions that apply when you
              use or purchase other services from us, which we will provide to
              you at the time of such use or subscribe.
            </p>
            <h6 className="py-2 fw-bold">Updates to our terms</h6>{" "}
            <p className="py-2">
              We may change our Service and policies, and we may need to make
              changes to these terms, so that the accurately reflect our Service
              and policies. Unless otherwise required by law, we will notify you
              (for example, through our service) before we make changes to these
              terms and give you an opportunity to review them before they go
              into effect. Then, if you continue to use the service, you will be
              bound by the updated terms. If you do not want to agree to these
              or any updated terms, you can delete your account.
            </p>
            <h6 className="py-2 fw-bold">Intellectual Property</h6>{" "}
            <p className="py-2">
              Our platform and its entire contents, features and functionality
              (including but limited to all information, software, text,
              displays, images, videos, and audio, and the design, selection and
              arrangement thereof), are owned by us, its licensors or other
              providers of such material and are protected by and international
              copyright, trademark, patent, trade secret and other intellectual
              property or proprietary right laws. The material may not be
              copied, modified, reproduced, downloaded, or redistributed in any
              way, in whole or in part, without the express prior written
              permission of us, unless and except as is expressly provided in
              these terms and conditions. Any unauthorized use of the material
              is prohibited.
            </p>
            <h6 className="py-2 fw-bold">Agreement to arbitrate</h6>{" "}
            <p className="py-2">
              This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A
              DISPUTE RELATING TO CLAIMS FOR ANY INJUCTIVE OR EQUITABLE RELIEF
              REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR INTELLECTUAL
              PROPERTY RIGHTS. The term “dispute” means any dispute, action, or
              other controversy between you and us concerning the Service or
              this agreement, whether in contract, warranty, tort, statute,
              regulation, ordinance, or any other legal or equitable basis.
              “Dispute” will be given the broadest possible meaning allowable
              under law.
            </p>
            <h6 className="py-2 fw-bold">Notice of dispute</h6>{" "}
            <p className="py-2">
              In the event of a dispute, you or us must give the other a Notice
              of Dispute, which is a written statement that sets forth the name,
              address, and contact information of the party giving it, the fact
              giving rise to the dispute, and the relief requested. You must
              send any Notice of Dispute via email to{" "}
              <a
                className=""
                href="info@thehunterswall.com"
                style={{ cursor: "pointer" }}
              >
                info@thehunterswall.com
              </a>
              . We will send any Notice of Dispute to you by mail to your
              address if we have it, or otherwise to your email address. You and
              us will attempt to resolve any dispute through informal
              negotiation within sixty (60) days from the date the Notice of
              Dispute is sent. After sixty (60) days, You or Us may commence
              arbitration.
            </p>
            <h6 className="py-2 fw-bold">Binding Arbitration</h6>{" "}
            <p className="py-2">
              If You and Us don’t resolve any dispute by informal negotiation,
              any other effort to resolve the dispute will be conducted
              exclusively by binding arbitration as described in this section.
              You ae giving up the right to litigate (or participate in as a
              party or class member) all dispute in court before a judge or
              jury.
            </p>
            <h6 className="py-2 fw-bold">Submissions and Privacy</h6>{" "}
            <p className="py-2">
              In the event that you submit or post any idea, creative
              suggestions, designs, photographs, information, advertisement,
              data or proposals, including ideas for new or improved products,
              services, features, technologies or promotions, you expressly
              agree that such submission will automatically be treated as
              non-confidential and non-proprietary and will become the sole
              property of us without any compensation or credit to you
              whatsoever. We and our affiliates shall have no obligations with
              respect to such submissions or posts and may use the ideas
              contained in such submissions or posts for any purposes in any
              medium in perpetuity, including, but not limited to developing,
              manufacturing, and marketing product and services using such
              ideas.
            </p>
            <h6 className="py-2 fw-bold">Promotions</h6>{" "}
            <p className="py-2">
              We may, from time to time, including contests, promotions, or
              other activities (“Promotions”) that require you to submit
              material or information concerning yourself. Please note that all
              promotions may be governed by separate rules that may contain
              certain eligibility requirements, such as restrictions as to age
              and geographical location. You are responsible to read all
              Promotions rules to determine whether or not you are eligible to
              participate. If you enter any Promotion, you agree to abide by and
              to comply with all promotions Rules. Addition terms and conditions
              may apply to purchase of goods and services on or through the
              Services which terms and conditions are made a part of this
              Agreement by this reference.
            </p>
            <h6 className="py-2 fw-bold">Typographical Errors</h6>{" "}
            <p className="py-2">
              In the event a product and/or service is listed at an incorrect
              price or with incorrect information due to typographical error, we
              shall have the right to refuse or cancel the product/service
              acquisition at the incorrect price. We shall have the right to
              refuse or cancel such order whether or not the order has been
              confirmed and your credit/debit card has already been charged for
              the purchase and your order is canceled, we shall immediately
              issue a credit to your credit/debit cards account or other
              payments account in the amount of the charge.
            </p>
            <h6 className="py-2 fw-bold">Miscellaneous</h6>{" "}
            <p className="py-2">
              If for any reason court of competent jurisdiction finds any
              provision or portion of these Terms and Conditions to be
              unenforceable, the remainder of these Terms & Conditions will
              continue in full force and effect. Any waiver of any provision f
              these terms & conditions will be effectively only if in written
              and signed by an authorized representative of us. We will be
              entitled to injunctive or other equitable relief (without the
              obligation of posting any bond or surety) in the event of any
              breach or anticipatory breach by you. We operate and control our
              Service from our offices. The service is not intended for
              distribution to or use by any person or entity in any jurisdiction
              or country where such distribution or use would be contrary to law
              or regulation. Accordingly, those persons who choose to access our
              Service from other locations do so on their own initiative and are
              solely responsible for compliance with local laws, if and to the
              extent local laws are applicable. These Terms & Conditions (which
              include and incorporate our Privacy Policy) contains the entire
              understanding, and supersedes all prior understandings, between
              you and us concerning its subject matter, and cannot be changed or
              modified by you. The section headings used in this Agreement are
              for convenience only and will not be given any legal import.
            </p>
            <h6 className="py-2 fw-bold">Disclaimer</h6>{" "}
            <p className="py-2">
              We are not responsible for any content, code, or any other
              imprecision. We do not provide warranties or guaranties. In no
              event shall we be liable for any special, direct, indirect,
              consequential, or incidental damages or any damage whatsoever,
              whether in an action of contract, negligence, or other tort,
              arising out of or in connection with the use of the service or its
              contents of the Service. We reserve the right to make additions,
              deletions, or modifications to the contents on the service at any
              time without prior notice.
              <br />
              <br /> Our Service and its contents are provided “as is” and “as
              available” without any warranty or representations of any kind,
              whether express or implied. We are a distributor not a publisher
              of the content supplied by third parties; as such, our exercises
              no editorial control over such content and makes no warranty or
              representation as to accuracy, reliability or currency of any
              information, content, service or merchandise provided through or
              accessible via our service. Without limiting the foregoing, we
              specifically disclaim all warranties and representations in any
              content transmitted or in connection with our service or on site
              that may appear as links on or service, or in the products
              provided as a part of, or otherwise in connection with, our
              Service, including without limitation any warranties of
              merchantability, fitness for a particular purpose or
              non-infringement of third-party rights. No oral advice or written
              information given by us or any of its affiliates, employees,
              officers, directors, agents, or the like will create a warranty.
              Price and availability information is subject to change without
              notice. Without limiting the foregoing, we do not warrant that our
              Service will be uninterrupted, uncorrupted, timely, or error-free.
            </p>
            <h6 className="py-2 fw-bold">Contact Us</h6>{" "}
            <p className="py-2">
              Don’t hesitate to contact us if you have any questions.
            </p>
            <ul>
              <li>Via Email: info@thehunterswall.com</li>
            </ul>
          </article>
        </div>
      </section>
    </Layout>
  );
}

export default terms;
